export const SITE_CONFIG = {
  name: 'OpenClaw',
  nameKo: 'AI 학습 플랫폼',
  description: 'AI와 프로그래밍을 배우는 종합 학습 플랫폼',
  url: 'https://openclaw.dreamitbiz.com',
  base: '/',
  author: 'DreamIT Biz',
  email: 'contact@dreamitbiz.com',
  github: 'https://github.com/aebonlee/openclaw',
};

export const LEARNING_PATHS = [
  {
    id: 'ai-fundamentals',
    icon: 'fa-brain',
    nameKo: 'AI 기초',
    nameEn: 'AI Fundamentals',
    descKo: '인공지능의 기본 개념과 원리를 학습합니다.',
    descEn: 'Learn the basic concepts and principles of AI.',
    color: '#4285F4',
    topics: ['머신러닝 기초', '딥러닝 개요', '자연어처리', '컴퓨터비전'],
  },
  {
    id: 'prompt-engineering',
    icon: 'fa-wand-magic-sparkles',
    nameKo: '프롬프트 엔지니어링',
    nameEn: 'Prompt Engineering',
    descKo: 'AI와 효과적으로 소통하는 프롬프트 작성법을 배웁니다.',
    descEn: 'Learn how to write effective prompts for AI.',
    color: '#10A37F',
    topics: ['기본 프롬프트', '고급 기법', '체인 오브 쏘트', '멀티턴 대화'],
  },
  {
    id: 'web-development',
    icon: 'fa-code',
    nameKo: '웹 개발',
    nameEn: 'Web Development',
    descKo: 'HTML, CSS, JavaScript부터 React까지 웹 개발을 학습합니다.',
    descEn: 'Learn web development from HTML/CSS/JS to React.',
    color: '#E34F26',
    topics: ['HTML/CSS', 'JavaScript', 'React', 'Node.js'],
  },
  {
    id: 'data-science',
    icon: 'fa-chart-line',
    nameKo: '데이터 사이언스',
    nameEn: 'Data Science',
    descKo: '데이터 분석과 시각화, 통계 기법을 학습합니다.',
    descEn: 'Learn data analysis, visualization, and statistics.',
    color: '#FF6F00',
    topics: ['Python 기초', '판다스', '데이터 시각화', '통계 분석'],
  },
  {
    id: 'python-programming',
    icon: 'fa-python',
    nameKo: 'Python 프로그래밍',
    nameEn: 'Python Programming',
    descKo: 'Python의 기초부터 고급 활용까지 체계적으로 학습합니다.',
    descEn: 'Systematically learn Python from basics to advanced.',
    color: '#3776AB',
    topics: ['변수와 자료형', '함수와 클래스', '파일 처리', '라이브러리 활용'],
  },
  {
    id: 'ai-tools-mastery',
    icon: 'fa-toolbox',
    nameKo: 'AI 도구 활용',
    nameEn: 'AI Tools Mastery',
    descKo: 'ChatGPT, Claude, Gemini 등 AI 도구를 실무에 활용합니다.',
    descEn: 'Master AI tools like ChatGPT, Claude, and Gemini.',
    color: '#8B5CF6',
    topics: ['ChatGPT 활용', 'Claude 활용', 'Gemini 활용', 'AI 자동화'],
  },
];
